### ISSUE TITLE
Fails to forward if index.php in URL on first load

### ISSUE THREAD

**Issue by halojoy** [enlivenapp/Open-Blog-3#59]
I did put Open-Blog-3 into my server.
http://server_root/openblog3/

So to install I did enter this:
http://server_root/openblog3/index.php

Result is an error because the header takes me to:
http://server_root/openblog3/index.php/installer/

There is a simple fix to avoid this, and it works in all cases I have tested.
Change **Line 56** in the index.php to:
`	header('Location: '.dirname($_SERVER['PHP_SELF']).'/installer/');`
(dirname($_SERVER['REQUEST_URI']) seems not work in this case.)

By the way I am working with a Swedish translation.
I have completed it to about 50%

**Comment by fontebasso** [comment]
Hello! Thank you for opening an issue with us!

I consider his adjustment to be valid for the context he presented. However, I believe in some reasons not to have the application in a directory of a primary domain.

Every application must have a unique virtualhost and in case of working with only one domain, use subdomains. However, I would like to understand how you understand this by working with the application in a subdirectory.

And immensely grateful to be helping with one more translation!!

**Comment by enlivenapp** [comment]
Hi @halojoy 

It would seem you found my unintentional assumption everyone first attempts to access a site without index.php first. While I haven't tested the theory yet, adding index.php to your URL would indeed engage the .htaccess file attempting to route the request, which would break the forward to the installer (if prerequisite files are not found).

While it arguably may or may not be a bug, I'm going to label it so as well as @fontebasso 's tag and we'll get it sorted asap.

Thanks for letting us know!

**Comment by enlivenapp** [comment]
Regarding the Swedish translation, I haven't added the CI core translations since they were quite old when I looked through that stuff.  It seems they've been updated in the last year.  I'll add them and update the database install file when you send your translation PR. 

Thanks!

**Comment by enlivenapp** [comment]
In researching the issue, I believe PHP_SELF will still cause a problem for some folks as it still contains `index.php` when it's in the URL.  Also see: https://stackoverflow.com/questions/279966/php-self-vs-path-info-vs-script-name-vs-request-uri

In fact, there's no real easy way to to get the base URL and drop the URI easily.  Here's what the open blog website reports when I have `/index.php` in the URL.

    // It's a sea of index.php  :/
    ...
    [SCRIPT_URL] => /index.php
    [SCRIPT_URI] => https://open-blog.org/index.php
    [HTTPS] => on
    [SSL_TLS_SNI] => open-blog.org
    [HTTP_HOST] => open-blog.org
    [HTTP_ACCEPT] => text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
    ...
    [SERVER_NAME] => open-blog.org
    ....
    [REDIRECT_URL] => /index.php
    [SERVER_PROTOCOL] => HTTP/1.1
    [REQUEST_METHOD] => GET
    [QUERY_STRING] => 
    [REQUEST_URI] => /index.php
    [SCRIPT_NAME] => /index.php
    [ORIG_PATH_INFO] => /index.php
    [PHP_SELF] => /index.php

So, while I could `if()` index.php is in there, and if there's an https connection, etc... I don't think that's something that needs to be decided in that detail every time the site is loaded.

I think the best way to work around this issue is to not put `index.php` in the URL.

Feel free to continue commenting as needed.
